name: Container image build and push

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Path to the Dockerfile'
        required: false
        type: string
        default: './Dockerfile'
      context:
        description: 'Build context path'
        required: false
        type: string
        default: '.'
      registry:
        description: 'Container registry URL (e.g., myregistry.azurecr.io). Uses secret.REGISTRY_LOGIN_SERVER if not provided'
        required: false
        type: string
        default: ''
      image-name:
        description: 'Image name (e.g., myapp)'
        required: true
        type: string
      image-tags:
        description: 'Space-separated list of tags (e.g., "latest v1.0.0")'
        required: false
        type: string
        default: 'latest'
      build-args:
        description: 'List of build-time variables (newline-delimited KEY=value pairs)'
        required: false
        type: string
        default: ''
      platforms:
        description: 'Comma-separated list of target platforms (e.g., linux/amd64,linux/arm64,linux/arm/v7). Common options: linux/amd64 (Intel/AMD 64-bit), linux/arm64 (ARM 64-bit), linux/arm/v7 (ARM 32-bit)'
        required: false
        type: string
        default: 'linux/amd64'
      push:
        description: 'Push image to registry'
        required: false
        type: boolean
        default: true
      runner:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'
      checkout-repository:
        description: 'Whether to checkout the repository'
        required: false
        type: boolean
        default: true
      registry-username:
        description: 'Container registry username or service principal ID (uses secret.REGISTRY_USERNAME if not provided)'
        required: false
        type: string
        default: ''
      registry-password:
        description: 'Container registry password or service principal secret (uses secret.REGISTRY_PASSWORD if not provided)'
        required: false
        type: string
        default: ''
    secrets:
      REGISTRY_LOGIN_SERVER:
        description: 'Container registry URL (optional, overridden by registry input)'
        required: false
      REGISTRY_USERNAME:
        description: 'Container registry username (optional, overridden by registry-username input)'
        required: false
      REGISTRY_PASSWORD:
        description: 'Container registry password (optional, overridden by registry-password input)'
        required: false
    outputs:
      image-digest:
        description: 'Image digest of the built container'
        value: ${{ jobs.build-and-push.outputs.digest }}
      image-tags:
        description: 'Full image tags that were pushed'
        value: ${{ jobs.build-and-push.outputs.tags }}

jobs:
  build-and-push:
    runs-on: ${{ inputs.runner }}
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        if: inputs.checkout-repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine registry variables
        id: registry-vars
        shell: bash
        run: |
          # Priority: inputs > secrets
          REGISTRY="${{ inputs.registry }}"
          if [ -z "$REGISTRY" ]; then
            REGISTRY="${{ secrets.REGISTRY_LOGIN_SERVER }}"
          fi
          
          USERNAME="${{ inputs.registry-username }}"
          if [ -z "$USERNAME" ]; then
            USERNAME="${{ secrets.REGISTRY_USERNAME }}"
          fi
          
          PASSWORD="${{ inputs.registry-password }}"
          if [ -z "$PASSWORD" ]; then
            PASSWORD="${{ secrets.REGISTRY_PASSWORD }}"
          fi
          
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry-vars.outputs.registry }}
          username: ${{ steps.registry-vars.outputs.username }}
          password: ${{ steps.registry-vars.outputs.password }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.registry-vars.outputs.registry }}/${{ inputs.image-name }}
          tags: ${{ inputs.image-tags }}

      - name: Build and push container image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image information
        run: |
          echo "### Container Build Summary 📦" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ steps.registry-vars.outputs.registry }}/${{ inputs.image-name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Digest:** \`${{ steps.build.outputs.digest }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "**Platforms:** \`${{ inputs.platforms }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Pushed:** \`${{ inputs.push }}\`" >> $GITHUB_STEP_SUMMARY
